name: pre-commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Create and activate virtual environment
      run: |
        uv venv
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        uv pip install pre-commit
    - name: Install pre-commit hooks
      run: |
        uv run pre-commit install
        uv run pre-commit install-hooks
    - name: Run pre-commit
      run: |
        uv run pre-commit run --all-files
